# Generated by Django 3.0.8 on 2020-08-02 03:49

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.CharField(blank=True, max_length=30)),
                ('instructor_first_name', models.CharField(max_length=300)),
                ('instructor_last_name', models.CharField(max_length=100, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=400)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('date_hired', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default=False, max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_pic', models.CharField(blank=True, max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('fax_no', models.CharField(blank=True, max_length=200)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], default=1)),
                ('dob', models.DateField()),
                ('preferred_language', models.CharField(blank=True, choices=[('EN', 'ENGLISH'), ('AR', 'ARABIC'), ('SP', 'SPANISH'), ('HI', 'HINDI'), ('FR', 'FRENCH'), ('RU', 'RUSSIAN')], default='EN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_id', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_no_students', models.CharField(max_length=50)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Instructor')),
            ],
        ),
    ]
